---
title: "Drop Procedure"
format: html
---

# Article selection procedure

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(dplyr)
library(ggplot2)
library(stringr)
library(gtsummary)
library(PRISMAstatement)
library(gt)
library(tidyr)

knitr::opts_chunk$set(echo = FALSE, warnings = FALSE, message = FALSE)
```

```{r}
df_papers <- read.csv("data/Papers imported_exported_1.csv")
colnames(df_papers)
df_final <- filter(df_papers,
    FinalSelected == "YES",
    Phase3DropReason == "",
    IsReview == FALSE)

df_final <- df_final %>%
    mutate(across(c(How.many.people, Hardware, Multi.user.technology, MeetingFrequency, Professional.Peer),
        # ~ sapply(str_split(., ","), str_trim) %>% toString(sort(.))))
        ~ purrr::map_chr(strsplit(., ",") , ~ str_trim(paste0(sort(str_trim(.x)), collapse=","))))) %>%
    mutate(multiuser_grouping = case_when(
               How.many.people %in% c("2") ~ "dyadic",
               TRUE ~ "multiuser"
    ))
df_final_multiuser <- df_final %>%
    filter(multiuser_grouping == "multiuser")
n_papers <- nrow(df_final)
```

```{r}
df_final %>%
    select(How.many.people) %>%
    tbl_summary()

df_final %>%
    select(DOI, multiuser_grouping, Professional.Peer) %>%
    separate_longer_delim(Professional.Peer, delim = ",") %>%
    count(multiuser_grouping, Professional.Peer) %>%
    gt()

df_final %>%
    select(DOI, multiuser_grouping, Multi.user.technology) %>%
    separate_longer_delim(Multi.user.technology, delim = ",") %>%
    count(multiuser_grouping, Multi.user.technology) %>%
    gt()

df_final %>%
    mutate(has_peer = ifelse(grepl("Peer", Professional.Peer), "Yes", "No"),
            has_professional = ifelse(grepl("Professional", Professional.Peer), "Yes", "No")) %>%
    separate_longer_delim(Multi.user.technology, delim = ",") %>%
    count(has_peer, Multi.user.technology) %>%
    group_by(has_peer) %>%
    gt() %>%
        tab_header(title = "Multi user technology for papers which have peer support groups")

df_final %>%
    mutate(has_peer = ifelse(grepl("Peer", Professional.Peer), "Yes", "No"),
            has_professional = ifelse(grepl("Professional", Professional.Peer), "Yes", "No")) %>%
    separate_longer_delim(Multi.user.technology, delim = ",") %>%
    count(has_professional, Multi.user.technology) %>%
    group_by(has_professional) %>%
    gt() %>%
        tab_header(title = "Multi user technology for papers which have professional oversight")

```


```{r}
df_final_multiuser %>%
    separate_longer_delim(Multi.user.technology, delim = ",") %>%
    group_by(Multi.user.technology) %>%
    summarise(n = n(), percent = n / n_papers * 100) %>%
    gt() %>%
    tab_header(title = "Multi-user technology used in the multiuser (2 and 3+ or 3+) papers")

df_final_multiuser %>%
    separate_longer_delim(Hardware, delim = ",") %>%
    group_by(Hardware) %>%
    summarise(n = n(), percent = n / n_papers * 100) %>%
    gt() %>%
    tab_header(title = "Multi-user technology used in the multiuser (2 and 3+ or 3+) papers")

df_final_multiuser %>%
    separate_longer_delim(Professional.Peer, delim = ",") %>%
    group_by(Professional.Peer) %>%
    summarise(n = n(), percent = n / n_papers * 100) %>%
    gt() %>%
    tab_header(title = "Professional peer support in the multiuser (2 and 3+ or 3+) papers")

df_final_multiuser %>%
    separate_longer_delim(MeetingFrequency, delim = ",") %>%
    group_by(MeetingFrequency) %>%
    summarise(n = n(), percent = n / n_papers * 100) %>%
    gt() %>%
    tab_header(title = "Meeting frequency in the multiuser (2 and 3+ or 3+) papers")
```
